-- Domain Tables: CUSTOMERS and ORDERS
-- Deploy to: Your agent's schema (e.g., <YOUR_DB>.<YOUR_AGENT_SCHEMA>)

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    NAME VARCHAR,
    EMAIL VARCHAR,
    CURRENT_TIER VARCHAR,
    SIGNUP_DATE DATE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0),
    ORDER_DATE DATE,
    AMOUNT NUMBER(12,2),
    STATUS VARCHAR,
    PRIMARY KEY (ORDER_ID)
);
